### ISSUE TITLE
Unable to get conversion result of android block

### ISSUE THREAD

**Issue by SakurajimaMaii** [cvb941/gradlekotlinize#1]
The conversion result is not displayed
![image](https://user-images.githubusercontent.com/46998172/204083139-84ebf062-3e84-48f2-8ba8-57577e0d133a.png)

**Comment by cvb941** [comment]
Hello,

The site has terrible UX now and no result means that there was an error during the conversion.

I will do something about it to make it more clear, in the meantime, paste a smaller part of the source until you start to get results.

**Comment by SakurajimaMaii** [comment]
Thank you very much for your reply, I will use your solution for now.
